version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: cybersecurity_app_1
    restart: always
    volumes:
      - media-root:/code/cybersecurity/media
    env_file:
      - .env
    command: ./manage.py runserver 0.0.0.0:8000 --settings=cybersecurity.settings.dev
    links:
      - redis:redis
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  db:
    restart: always
    image: postgres:15-alpine
    container_name: cybersecurity_db_1
    volumes:
      - cybersecurity_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env

  redis:
    restart: always
    image: redis:6.2
    container_name: cybersecurity_redis_1
    expose:
      - '6379'

#  elasticsearch:
#    # restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
#    container_name: es01
#    ports:
#      - '9200:9200'
#      - '9300:9300'
#    environment:
#      - xpack.security.enabled=false
#      - discovery.type=single-node
#      # - xpack.license.self_generated.type=basic
#      - ELASTIC_PASSWORD=22rMw/22D
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    cap_add:
#      - IPC_LOCK
#    volumes:
#      - elasticsearch-data:/usr/share/elasticsearch/data
#    healthcheck:
#      test:
#        [
#          "CMD-SHELL",
#          "curl https://localhost:9200 | grep -q 'missing authentication credentials'",
#        ]
#      interval: 10s
#      timeout: 10s
#      retries: 120

volumes:
  media-root:
  cybersecurity_db:
  elasticsearch-data:
