# Generated by Django 4.0.8 on 2022-11-01 23:12

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_standardpage_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='person',
            field=wagtail.fields.StreamField([('team', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Titel', required=False)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('name', wagtail.blocks.CharBlock(blank=True, help_text='Name', max_length=40, null=True)), ('role', wagtail.blocks.CharBlock(blank=True, help_text='Role', max_length=20, null=True)), ('text', wagtail.blocks.RichTextBlock(blank=True, help_text='Textblock', null=True))])))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
